# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: face-rcognition-cnn
provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: face-rcognition-cnn-dev-serverlessdeploymentbucke-1tlu1wthbdx78
    MODEL_PATH: face_recognition.pt
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:getObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetObjectAcl"
      Resource: arn:aws:s3:::face-rcognition-cnn-dev-serverlessdeploymentbucke-1tlu1wthbdx78/face_recognition.pt

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: false
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  face_reco_cnn:
    handler: handler.face_reco_cnn
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: face_reco_cnn
          method: post
          cors: true

plugins:
  - serverless-python-requirements
